databases:
  - name: pmtool-db
    plan: free
    databaseName: pmtool
    user: pmtool

services:
  - type: web
    name: pmtool
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pmtool-db
          property: connectionString
